export const FETCH_OPPORTUNITIES = "FETCH_OPPORTUNITIES";
export const CREATE_OPPORTUNITY = "CREATE_OPPORTUNITY";
export const DELETE_OPPORTUNITY = "DELETE_OPPORTUNITY";
export const UPDATE_OPPORTUNITY = "UPDATE_OPPORTUNITY";

//AUTH ACTIONS
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const REGISTER_USER = "REGISTER_USER";
export const AUTH_ERROR = "AUTH_ERROR";
