export const FETCH_OPPORTUNITIES = "FETCH_OPPORTUNITIES";
export const NEW_OPPORTUNITY = "NEW_OPPORTUNITY";

//AUTH ACTIONS
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const REGISTER_USER = "REGISTER_USER";
export const AUTH_ERROR = "AUTH_ERROR";
